### ISSUE TITLE
tabs_on_bottom_v2.css no close, minimize, maximize button.

### ISSUE THREAD

**Issue by l3ifk** [MrOtherGuy/firefox-csshacks#580]
As the title says, with Firefox version 143.0.4 and the tabs_on_bottom_v2.css the 3 control buttons on the top right of the window disappear. They are just gone. (see screenshot)

<img width="407" height="106" alt="Image" src="https://github.com/user-attachments/assets/162c63c6-605f-4fd0-a480-e6562fa6e7ac" />

**Comment by MrOtherGuy** [comment]
Okay, so it's native Windows native titlebar. When native titlebar is enabled, then window controls are in it and are not affected by userChrome.css, thus I'm pretty sure you would experience this issue without any userCrome.css at all. 

I read about some bug reports where on some Windows systems then native titlebar had some issues, this might be related to that. If I recall, the issue should be fixed in 147.

Nonetheless, I don't think this is in any way related to tabs_on_bottom_v2.css

**Comment by Atexor** [comment]
After few months and Firefox releases (currently v150.0.1) the issue still exists. After removing tabs_on_bottom_v2.css it works fine.
I opened issue on Firefox bugtracker, but they cannot replicate it which is understandable, because even in my case it occurs only on one computer.
